function t228_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t228__list_item a[href='"+url+"']").addClass("t-active");$(".t228__list_item a[href='"+url+"/']").addClass("t-active");$(".t228__list_item a[href='"+pathname+"']").addClass("t-active");$(".t228__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t228__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t228__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t228_checkAnchorLinks(recid){if($(window).width()>=960){var t228_navLinks=$("#rec"+recid+" .t228__list_item a:not(.tooltipstered)[href*='#']");if(t228_navLinks.length>0){t228_catchScroll(t228_navLinks)}}}
function t228_catchScroll(t228_navLinks){var t228_clickedSectionId=null,t228_sections=new Array(),t228_sectionIdTonavigationLink=[],t228_interval=100,t228_lastCall,t228_timeoutId;t228_navLinks=$(t228_navLinks.get().reverse());t228_navLinks.each(function(){var t228_cursection=t228_getSectionByHref($(this));if(typeof t228_cursection.attr("id")!="undefined"){t228_sections.push(t228_cursection)}
t228_sectionIdTonavigationLink[t228_cursection.attr("id")]=$(this)});t228_updateSectionsOffsets(t228_sections);t228_sections.sort(function(a,b){return b.attr("data-offset-top")-a.attr("data-offset-top")});$(window).bind('resize',t_throttle(function(){t228_updateSectionsOffsets(t228_sections)},200));$('.t228').bind('displayChanged',function(){t228_updateSectionsOffsets(t228_sections)});setInterval(function(){t228_updateSectionsOffsets(t228_sections)},5000);t228_highlightNavLinks(t228_navLinks,t228_sections,t228_sectionIdTonavigationLink,t228_clickedSectionId);t228_navLinks.click(function(){var t228_clickedSection=t228_getSectionByHref($(this));if(!$(this).hasClass("tooltipstered")&&typeof t228_clickedSection.attr("id")!="undefined"){t228_navLinks.removeClass('t-active');$(this).addClass('t-active');t228_clickedSectionId=t228_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t228_now=new Date().getTime();if(t228_lastCall&&t228_now<(t228_lastCall+t228_interval)){clearTimeout(t228_timeoutId);t228_timeoutId=setTimeout(function(){t228_lastCall=t228_now;t228_clickedSectionId=t228_highlightNavLinks(t228_navLinks,t228_sections,t228_sectionIdTonavigationLink,t228_clickedSectionId)},t228_interval-(t228_now-t228_lastCall))}else{t228_lastCall=t228_now;t228_clickedSectionId=t228_highlightNavLinks(t228_navLinks,t228_sections,t228_sectionIdTonavigationLink,t228_clickedSectionId)}})}
function t228_updateSectionsOffsets(sections){$(sections).each(function(){var t228_curSection=$(this);t228_curSection.attr("data-offset-top",t228_curSection.offset().top)})}
function t228_getSectionByHref(curlink){var t228_curLinkValue=curlink.attr("href").replace(/\s+/g,'');if(t228_curLinkValue[0]=='/'){t228_curLinkValue=t228_curLinkValue.substring(1)}
if(curlink.is('[href*="#rec"]')){return $(".r[id='"+t228_curLinkValue.substring(1)+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+t228_curLinkValue.substring(1)+"']")}}
function t228_highlightNavLinks(t228_navLinks,t228_sections,t228_sectionIdTonavigationLink,t228_clickedSectionId){var t228_scrollPosition=$(window).scrollTop(),t228_valueToReturn=t228_clickedSectionId;if(t228_sections.length!=0&&t228_clickedSectionId==null&&t228_sections[t228_sections.length-1].attr("data-offset-top")>(t228_scrollPosition+300)){t228_navLinks.removeClass('t-active');return null}
$(t228_sections).each(function(e){var t228_curSection=$(this),t228_sectionTop=t228_curSection.attr("data-offset-top"),t228_id=t228_curSection.attr('id'),t228_navLink=t228_sectionIdTonavigationLink[t228_id];if(((t228_scrollPosition+300)>=t228_sectionTop)||(t228_sections[0].attr("id")==t228_id&&t228_scrollPosition>=$(document).height()-$(window).height())){if(t228_clickedSectionId==null&&!t228_navLink.hasClass('t-active')){t228_navLinks.removeClass('t-active');t228_navLink.addClass('t-active');t228_valueToReturn=null}else{if(t228_clickedSectionId!=null&&t228_id==t228_clickedSectionId){t228_valueToReturn=null}}
return!1}});return t228_valueToReturn}
function t228_setPath(){}
function t228_setWidth(recid){var window_width=$(window).width();if(window_width>980){$(".t228").each(function(){var el=$(this);var left_exist=el.find('.t228__leftcontainer').length;var left_w=el.find('.t228__leftcontainer').outerWidth(!0);var max_w=left_w;var right_exist=el.find('.t228__rightcontainer').length;var right_w=el.find('.t228__rightcontainer').outerWidth(!0);var items_align=el.attr('data-menu-items-align');if(left_w<right_w)max_w=right_w;max_w=Math.ceil(max_w);var center_w=0;el.find('.t228__centercontainer').find('li').each(function(){center_w+=$(this).outerWidth(!0)});var padd_w=40;var maincontainer_width=el.find(".t228__maincontainer").outerWidth(!0);if(maincontainer_width-max_w*2-padd_w*2>center_w+20){if(items_align=="center"||typeof items_align==="undefined"){el.find(".t228__leftside").css("min-width",max_w+"px");el.find(".t228__rightside").css("min-width",max_w+"px");el.find(".t228__list").removeClass("t228__list_hidden")}}else{el.find(".t228__leftside").css("min-width","");el.find(".t228__rightside").css("min-width","")}})}}
function t228_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t228").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t228").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t228_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t228").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t228_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t228").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||(typeof menushadow=="undefined"&&menushadow==!1)){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||(typeof menushadow=="undefined"&&menushadow==!1)){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t228_createMobileMenu(recid){var window_width=$(window).width(),el=$("#rec"+recid),menu=el.find(".t228"),burger=el.find(".t228__mobile");burger.click(function(e){menu.fadeToggle(300);$(this).toggleClass("t228_opened")})
$(window).bind('resize',t_throttle(function(){window_width=$(window).width();if(window_width>980){menu.fadeIn(0)}},200))}
function t347_setHeight(recid){var el=$('#rec'+recid);var div=el.find(".t347__table");var height=div.width()*0.5625;div.height(height)}
window.t347showvideo=function(recid){$(document).ready(function(){var el=$('#rec'+recid);var videourl='';var youtubeid=$("#rec"+recid+" .t347__video-container").attr('data-content-popup-video-url-youtube');if(youtubeid>''){videourl='https://www.youtube.com/embed/'+youtubeid}
$("#rec"+recid+" .t347__video-container").removeClass("t347__hidden");$("#rec"+recid+" .t347__video-carier").html("<iframe id=\"youtubeiframe"+recid+"\" class=\"t347__iframe\" width=\"100%\" height=\"100%\" src=\""+videourl+"?autoplay=1\" frameborder=\"0\" allowfullscreen></iframe>")})}
window.t347hidevideo=function(recid){$(document).ready(function(){$("#rec"+recid+" .t347__video-container").addClass("t347__hidden");$("#rec"+recid+" .t347__video-carier").html("")})}
t431_createTable=function(recid,tablehead,tabledata,tablecolsize,hastargetblank,btnstyles,t431__tdstyles,t431__thstyles,t431__oddrowstyles,t431__evenrowstyles){var t431__arrayColSize=t431_parseData(tablecolsize);var t431__arrayHead=t431_parseData(tablehead);var t431__arrayData=t431_parseData(tabledata);var t431__maxcolnumber=t431__findMaxRowLengthInTable(t431__arrayHead,t431__arrayData);var t431__colWidth=t431__setColumnsWidth(t431__arrayColSize,t431__maxcolnumber,recid);if(t431__colWidth[0].myText&&t431__colWidth[0].myText[t431__colWidth[0].myText.length-1]=="%"){for(var i=0;i<t431__colWidth.length;i++){t431__colWidth[i].myText=t431__colWidth[i].myText.slice(0,-1);t431__colWidth[i].myText+="vw"}}
var t431__container=$('#rec'+recid+' .t431 .t-container .t431__table');var t431__htmlTable="";if(t431__arrayHead){t431__htmlTable+=t431__generateHtml(recid,t431__arrayHead,"th",hastargetblank,t431__colWidth,btnstyles,t431__thstyles,null,null,t431__maxcolnumber)}
t431__container.append(t431__htmlTable);t431__htmlTable="";if(t431__arrayData){t431__htmlTable+=t431__generateHtml(recid,t431__arrayData,"td",hastargetblank,t431__colWidth,btnstyles,t431__tdstyles,t431__oddrowstyles,t431__evenrowstyles,t431__maxcolnumber)}
t431__container.append(t431__htmlTable)};t431_setHeadWidth=function(recid){if($(window).width()>960){var t431__tbody=$('#rec'+recid+' .t431 .t431__tbody');var t431__thead=$('#rec'+recid+' .t431 .t431__thead');t431__tbody.css("display","block");t431__thead.css("display","block");var t431__colWidth=$('#rec'+recid+' .t431 .t431__tbody tr:first').children().map(function(){return $(this).width()});if($('#rec'+recid+' .t431 .t431__tbody tr td:first').css('border-left-width').length>=3){var t431__verticalborder=$('#rec'+recid+' .t431 .t431__tbody tr td:first').css('border-left-width').slice(0,-2)}
$('#rec'+recid+' .t431 .t431__thead tr').children().each(function(i,v){if($(v).is(":last-child")){$(v).width(t431__colWidth[i]+(t431__tbody.width()-$('#rec'+recid+' .t431 .t431__tbody tr:first').width()))}else{$(v).width(t431__colWidth[i]+(+t431__verticalborder))}})}};t431__findMaxRowLengthInTable=function(arrayhead,arraydata){var t431__headmaxlength=0;var t431__datamaxlength=0;if(arrayhead){t431__headmaxlength=t431__findMaxRowLengInArray(arrayhead)}
if(arraydata){t431__datamaxlength=t431__findMaxRowLengInArray(arraydata)}
if(t431__datamaxlength>t431__headmaxlength){return t431__datamaxlength}else{return t431__headmaxlength}};t431__findMaxRowLengInArray=function(curarray){var t431__maxlength=0;for(var i=0;i<curarray.length;i++){if(curarray[i].length>t431__maxlength){t431__maxlength=curarray[i].length}}
return t431__maxlength};t431__setColumnsWidth=function(t431__colwidth,t431__colsnumber,recid){if(t431__colwidth){return t431__colwidth[0]}else{var t431__tablewidth=$('#rec'+recid+' .t431 .t-container .t-col').width();return(t431__tablewidth/t431__colsnumber+"px")}};t431__generateHtml=function(recid,arrayValues,coltag,hastargetblank,colWidth,btnstyles,colstyles,oddrowstyles,evenrowstyles,maxcolnumber){var t431__htmlpart="";if(coltag=="td"){var t431__theadorbodytag="tbody"}else{var t431__theadorbodytag="thead"}
t431__htmlpart+="<"+t431__theadorbodytag+" class=\"t431__"+t431__theadorbodytag+"\">";if($('#rec'+recid+' .t431 .t-container .t431__thead th').length>0&&$('#rec'+recid+' .t431 .t-container .t431__thead th').css("border-bottom-width")[0]!="0"){var t431__firstbodyrowstyle="border-top: 0 !important;"}
for(var i=0;i<arrayValues.length;i++){if(coltag=="td"){if((i+1)%2>0){t431__htmlpart+="<tr class=\"t431__oddrow\""+"style=\""+oddrowstyles+"\">"}else{t431__htmlpart+="<tr class=\"t431__evenrow\""+"style=\""+evenrowstyles+"\">"}}else{t431__htmlpart+="<tr>"}
var t431__addingcols=0;if(arrayValues[i].length<maxcolnumber){t431__addingcols=maxcolnumber-arrayValues[i].length}
for(var j=0;j<(arrayValues[i].length+t431__addingcols);j++){if(arrayValues[i][j]){if(Array.isArray(colWidth)&&colWidth[j]){var t431__curWidth=colWidth[j].myText}else{var t431__curWidth=colWidth}
if(i==0&&coltag=="td"){var t431__colwithattr="<"+coltag+" class=\"t431__"+coltag+"\" style=\"width:"+t431__curWidth+";"+colstyles+t431__firstbodyrowstyle+"\">"}else{var t431__colwithattr="<"+coltag+" class=\"t431__"+coltag+"\" style=\"width:"+t431__curWidth+";"+colstyles+"\">"}
if(arrayValues[i][j].myHref){var t431__tblank="";if(hastargetblank){var t431__tblank="target=\"_blank\""}
if(arrayValues[i][j].myHrefType=="link"){var t431__linkwithattr="<a href=\""+arrayValues[i][j].myHref+"\""+t431__tblank+">";var t431__linkclosetag="</a>"}else{var t431__linkwithattr="<div class=\"t431__btnwrapper\"><a href=\""+arrayValues[i][j].myHref+"\""+t431__tblank+" class=\"t-btn t-btn_sm\" style=\""+btnstyles+"\"><table style=\"width:100%; height:100%;\"><tr><td>";var t431__linkclosetag="</td></tr></table></a></div>"}
t431__htmlpart+=t431__colwithattr+t431__linkwithattr+arrayValues[i][j].myText+t431__linkclosetag+"</"+coltag+">"}else{t431__htmlpart+=t431__colwithattr+arrayValues[i][j].myText+"</"+coltag+">"}}else{t431__htmlpart+="<"+coltag+" class=\"t431__"+coltag+"\" style=\"width:"+t431__curWidth+";"+colstyles+"\">"+"</"+coltag+">"}}
t431__htmlpart+="</tr>"}
t431__htmlpart+="</"+t431__theadorbodytag+">";return t431__htmlpart};t431_parseData=function(t431__data){if(t431__data!=""&&typeof t431__data!='undefined')
{t431__data=t431__addBrTag(t431__data);var t431__arrayTable=new Array();var t431__arrayRow=new Array();var t431__curItem={myText:"",myHref:"",myHrefType:""};var t431__HasLink="";var t431__HasLinkWithSpace="";var t431__HasBtn="";var t431__HasBtnWithSpace="";var t431__EndOfLine="";for(var i=0;i<t431__data.length;i++)
{if(t431__data[i]==";"&&!((t431__data[i-1]&&(t431__data[i-1]=="t"))&&(t431__data[i-2]&&(t431__data[i-2]=="g"||t431__data[i-2]=="l"))&&(t431__data[i-3]&&(t431__data[i-3]=="&")))&&!((t431__data[i-1]&&(t431__data[i-1]=="p"))&&(t431__data[i-2]&&(t431__data[i-2]=="m"))&&(t431__data[i-3]&&(t431__data[i-3]=="a"))&&(t431__data[i-4]&&(t431__data[i-4]=="&")))){t431__arrayRow.push(t431__curItem);var t431__curItem={myText:"",myHref:""};t431__HasLink="";t431__HasLinkWithSpace="";t431__HasBtn="";t431__HasBtnWithSpace=""}else{if(t431__HasLink=="link="||t431__HasLinkWithSpace==" link="||t431__HasBtn=="button="||t431__HasBtnWithSpace==" button="){if(t431__curItem.myHref==""&&t431__HasLink=="link="){t431__curItem.myText=t431__curItem.myText.slice(0,-5);t431__curItem.myHrefType="link"}else{if(t431__curItem.myHref==""&&t431__HasLinkWithSpace==" link="){t431__curItem.myText=t431__curItem.myText.slice(0,-6);t431__curItem.myHrefType="link"}else{if(t431__curItem.myHref==""&&t431__HasBtn=="button="){t431__curItem.myText=t431__curItem.myText.slice(0,-7);t431__curItem.myHrefType="btn"}else{if(t431__curItem.myHref==""&&t431__HasBtnWithSpace==" button="){t431__curItem.myText=t431__curItem.myText.slice(0,-8);t431__curItem.myHrefType="btn"}}}}
t431__curItem.myHref+=(t431__data[i])}else{t431__curItem.myText+=(t431__data[i]);t431__HasLink=t431__checkSubstr("link=",t431__HasLink,t431__data[i]);t431__HasLinkWithSpace=t431__checkSubstr(" link=",t431__HasLinkWithSpace,t431__data[i]);t431__HasBtn=t431__checkSubstr("button=",t431__HasBtn,t431__data[i]);t431__HasBtnWithSpace=t431__checkSubstr(" button=",t431__HasBtnWithSpace,t431__data[i])}
t431__EndOfLine=t431__checkSubstr("<br />",t431__EndOfLine,t431__data[i]);if(t431__EndOfLine=="<br />"){if(t431__curItem.myHref){t431__curItem.myHref=t431__curItem.myHref.slice(0,-6)}else{t431__curItem.myText=t431__curItem.myText.slice(0,-6)}
t431__arrayRow.push(t431__curItem);t431__arrayTable.push(t431__arrayRow);var t431__curItem={myText:"",myHref:""};t431__HasLink="";t431__HasLinkWithSpace="";t431__HasBtn="";t431__HasBtnWithSpace="";t431__arrayRow=new Array()}}}
if(t431__arrayRow.length>0||t431__curItem.myText!=""){if(t431__curItem!=""){t431__arrayRow.push(t431__curItem)}
t431__arrayTable.push(t431__arrayRow)}}
return t431__arrayTable};t431__checkSubstr=function(t431__targetSubstr,t431__curSubstr,t431__curSymbol){if(!t431__curSubstr&&t431__curSymbol==t431__targetSubstr[0]){return t431__curSymbol}else{if(t431__curSubstr){for(var i=0;i<(t431__targetSubstr.length-1);i++){if(t431__curSubstr[t431__curSubstr.length-1]==t431__targetSubstr[i]&&t431__curSymbol==t431__targetSubstr[i+1]){return(t431__curSubstr+=t431__curSymbol)}}}}};t431__addBrTag=function(t431__oldStringItem){if(typeof t431__oldStringItem=='undefined')return;var t431__newStringItem="";for(var i=0;i<t431__oldStringItem.length;i++){if(t431__oldStringItem[i]=="\n"||t431__oldStringItem[i]=="\r"){t431__newStringItem+="<br />"}else{t431__newStringItem+=t431__oldStringItem[i]}}
return t431__newStringItem};function t577_equalHeight(recid){var el=$('#rec'+recid);el.find('.t577').css('visibility','visible');el.find('.t577__textwrapper').css('height','auto');el.find('.t577__descr').css('height','auto');$('#rec'+recid+' .t577__row').each(function(){var highestBox=0;$('.t577__descr',this).each(function(){if($(this).height()>highestBox)highestBox=$(this).height()});if($(window).width()>=960&&$(this).is(':visible')){$('.t577__descr',this).css('height',highestBox)}else{$('.t577__descr',this).css('height',"auto")}});$('#rec'+recid+' .t577__row').each(function(){var highestBox=0;$('.t577__textwrapper',this).each(function(){if($(this).height()>highestBox)highestBox=$(this).height()});if($(window).width()>=960&&$(this).is(':visible')){$('.t577__textwrapper',this).css('height',highestBox)}else{$('.t577__textwrapper',this).css('height',"auto")}})}